Completed Work
SOsdoba/The-Bakery pull request #2
Opened 2023-01-26 09:10 UTC by AvigailGellis

Here are my changes, review the work and comment in the conversation tab of the pull request.

2023-01-27 01:01 UTC, SOsdoba requested changes
I added some comments to the table and reports files.

2023-01-27 01:01 UTC, SOsdoba commented on BakeryDB/1 tables.sql
> +    constraint ck_Orders_DateOrdered_must_be_before_DateNeeded check(DateOrdered < DateNeeded),
I don't think you need this constraint, as the following constraint already takes care of the DateOrdered being before the DateNeeded.

2023-01-27 01:01 UTC, SOsdoba commented on BakeryDB/1 tables.sql
> +    CreditCardNum char(4) not null constraint ck_Orders_CreditCardNum_must_be_numbers check(CreditCardNum like ('[0-9][0-9][0-9][0-9]') or CreditCardNum = ''),
There should be a constraint that ensures that CreditCardNum only allows blank when the payment method is cash.

2023-01-27 01:01 UTC, SOsdoba commented on BakeryDB/1 tables.sql
> +    PricePerUnit decimal(6,2) not null constraint ck_Orders_PricePerUnit_must_be_between_2_dollars_and_50_cents_and_650_dollars check(PricePerUnit between 2.5 and 650),
I don't think it's necessary to allow for 4 digits on the left side of the decimal as the most we will charge is $650, which would only make it necessary for 3 digits on the left side of the decimal.

2023-01-27 01:01 UTC, SOsdoba commented on BakeryDB/3 reports.sql
> +select count(*), AvgSpent = avg(o.TotalCost), o.PaymentType
The first column needs a name.

2023-01-27 01:01 UTC, SOsdoba commented on BakeryDB/3 reports.sql
> +select LossPerMonth = sum(o.TotalCost) - sum(case when datepart(day, o.DateOrdered) in(1,15) and o.Quantity > 1 then (o.Quantity / 2) * o.PricePerUnit else o.TotalCost end), datename(month, o.DateOrd
The column with the months need a name.

2023-01-30 08:27 UTC, AvigailGellis commented on BakeryDB/1 tables.sql
> +    constraint ck_Orders_DateOrdered_must_be_before_DateNeeded check(DateOrdered < DateNeeded),
Fixed.

2023-01-30 08:27 UTC, AvigailGellis commented on BakeryDB/1 tables.sql
> +    CreditCardNum char(4) not null constraint ck_Orders_CreditCardNum_must_be_numbers check(CreditCardNum like ('[0-9][0-9][0-9][0-9]') or CreditCardNum = ''),
Fixed.

2023-01-30 08:27 UTC, AvigailGellis commented on BakeryDB/1 tables.sql
> +    PricePerUnit decimal(6,2) not null constraint ck_Orders_PricePerUnit_must_be_between_2_dollars_and_50_cents_and_650_dollars check(PricePerUnit between 2.5 and 650),
Fixed.

2023-01-30 08:28 UTC, AvigailGellis commented on BakeryDB/3 reports.sql
> +select count(*), AvgSpent = avg(o.TotalCost), o.PaymentType
Fixed.

2023-01-30 08:28 UTC, AvigailGellis commented on BakeryDB/3 reports.sql
> +select LossPerMonth = sum(o.TotalCost) - sum(case when datepart(day, o.DateOrdered) in(1,15) and o.Quantity > 1 then (o.Quantity / 2) * o.PricePerUnit else o.TotalCost end), datename(month, o.DateOrd
Fixed.

2023-02-02 15:24 UTC, SOsdoba commented on BakeryDB/1 tables.sql
> +    PricePerUnit decimal(6,2) not null constraint ck_Orders_PricePerUnit_must_be_between_2_dollars_and_50_cents_and_650_dollars check(PricePerUnit between 2.5 and 650),
Great

2023-02-02 15:24 UTC, SOsdoba commented on BakeryDB/1 tables.sql
> +    CreditCardNum char(4) not null constraint ck_Orders_CreditCardNum_must_be_numbers check(CreditCardNum like ('[0-9][0-9][0-9][0-9]') or CreditCardNum = ''),
Great

2023-02-02 15:24 UTC, SOsdoba commented on BakeryDB/3 reports.sql
> +select count(*), AvgSpent = avg(o.TotalCost), o.PaymentType
Great

2023-02-02 15:24 UTC, SOsdoba commented on BakeryDB/3 reports.sql
> +select LossPerMonth = sum(o.TotalCost) - sum(case when datepart(day, o.DateOrdered) in(1,15) and o.Quantity > 1 then (o.Quantity / 2) * o.PricePerUnit else o.TotalCost end), datename(month, o.DateOrd
Great

2023-02-02 15:24 UTC, SOsdoba commented on BakeryDB/1 tables.sql
> +    constraint ck_Orders_DateOrdered_must_be_before_DateNeeded check(DateOrdered < DateNeeded),
great

2023-02-02 17:16 UTC, closed without merging